"""Generate the two colour-space .cube LUTs rmidi loads onto nodes.

  A: S-Gamut3.Cine / S-Log3        -> DaVinci Wide Gamut / DaVinci Intermediate
  B: DaVinci Wide Gamut / DaVinci Intermediate -> Rec.709 / Gamma 2.4

All constants are the published Sony and Blackmagic values; the gamut matrices are
derived from primaries + white point rather than copied, so they are exact.
"""
import math, os, sys

# ---------- primaries (x, y) and white points ----------
SGAMUT3_CINE = ((0.766, 0.275), (0.225, 0.800), (0.089, -0.087))
DAVINCI_WG   = ((0.8000, 0.3130), (0.1682, 0.9877), (0.0790, -0.1155))
REC709       = ((0.640, 0.330), (0.300, 0.600), (0.150, 0.060))
D65          = (0.3127, 0.3290)


def _inv3(m):
    a, b, c = m[0]; d, e, f = m[1]; g, h, i = m[2]
    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    if abs(det) < 1e-12:
        raise ValueError("singular matrix")
    return [[(e * i - f * h) / det, (c * h - b * i) / det, (b * f - c * e) / det],
            [(f * g - d * i) / det, (a * i - c * g) / det, (c * d - a * f) / det],
            [(d * h - e * g) / det, (b * g - a * h) / det, (a * e - b * d) / det]]


def _mul3(m, n):
    return [[sum(m[r][k] * n[k][col] for k in range(3)) for col in range(3)] for r in range(3)]


def rgb_to_xyz(prim, white):
    """Derive the RGB->XYZ matrix from chromaticities (Wyszecki & Stiles method)."""
    cols = []
    for x, y in prim:
        cols.append([x / y, 1.0, (1.0 - x - y) / y])
    M = [[cols[c][r] for c in range(3)] for r in range(3)]
    xw, yw = white
    W = [xw / yw, 1.0, (1.0 - xw - yw) / yw]
    Minv = _inv3(M)
    S = [sum(Minv[r][k] * W[k] for k in range(3)) for r in range(3)]
    return [[M[r][c] * S[c] for c in range(3)] for r in range(3)]


def gamut_matrix(src_prim, dst_prim, white=D65):
    """src RGB -> dst RGB. Both share D65, so no chromatic adaptation is needed."""
    return _mul3(_inv3(rgb_to_xyz(dst_prim, white)), rgb_to_xyz(src_prim, white))


# ---------- transfer functions ----------
def slog3_to_lin(x):
    """Sony S-Log3 -> scene linear reflection (official Sony formula)."""
    if x >= 171.2102946929 / 1023.0:
        return (10.0 ** ((x * 1023.0 - 420.0) / 261.5)) * (0.18 + 0.01) - 0.01
    return (x * 1023.0 - 95.0) * 0.01125000 / (171.2102946929 - 95.0)


# Blackmagic DaVinci Intermediate constants
DI_A, DI_B, DI_C = 0.0075, 7.0, 0.07329248
DI_M, DI_LIN_CUT, DI_LOG_CUT = 10.44426855, 0.00262409, 0.02740668


def lin_to_di(x):
    if x <= DI_LIN_CUT:
        return x * DI_M
    return (math.log2(x + DI_A) + DI_B) * DI_C


def di_to_lin(x):
    if x <= DI_LOG_CUT:
        return x / DI_M
    return 2.0 ** (x / DI_C - DI_B) - DI_A


def lin_to_g24(x):
    return max(x, 0.0) ** (1.0 / 2.4)


# ---------- LUT writers ----------
def write_cube(path, size, fn, title):
    with open(path, "w") as f:
        f.write(f"# {title}\n")
        f.write(f"# generated by rmidi - do not edit by hand\n")
        f.write(f'TITLE "{title}"\n')
        f.write(f"LUT_3D_SIZE {size}\n")
        f.write("DOMAIN_MIN 0.0 0.0 0.0\n")
        f.write("DOMAIN_MAX 1.0 1.0 1.0\n")
        d = size - 1
        for b in range(size):
            for g in range(size):
                for r in range(size):
                    o = fn(r / d, g / d, b / d)
                    f.write(f"{o[0]:.6f} {o[1]:.6f} {o[2]:.6f}\n")


def apply3(m, v):
    return [sum(m[r][c] * v[c] for c in range(3)) for r in range(3)]


SG3C_TO_DWG = gamut_matrix(SGAMUT3_CINE, DAVINCI_WG)
DWG_TO_709 = gamut_matrix(DAVINCI_WG, REC709)


def slog3_to_dwg_di(r, g, b):
    lin = [slog3_to_lin(r), slog3_to_lin(g), slog3_to_lin(b)]
    wide = apply3(SG3C_TO_DWG, lin)
    # lin_to_di is linear below LIN_CUT, so negatives never reach log2(); clamp after.
    return [min(max(lin_to_di(v), 0.0), 1.0) for v in wide]


def dwg_di_to_rec709_g24(r, g, b):
    lin = [di_to_lin(r), di_to_lin(g), di_to_lin(b)]
    out = apply3(DWG_TO_709, lin)
    return [min(lin_to_g24(v), 1.0) for v in out]


if __name__ == "__main__":
    size = int(sys.argv[1]) if len(sys.argv) > 1 else 33
    outdir = sys.argv[2] if len(sys.argv) > 2 else "."
    os.makedirs(outdir, exist_ok=True)
    print("S-Gamut3.Cine -> DaVinci WG matrix:")
    for row in SG3C_TO_DWG:
        print("   ", " ".join(f"{v: .6f}" for v in row))
    print("DaVinci WG -> Rec.709 matrix:")
    for row in DWG_TO_709:
        print("   ", " ".join(f"{v: .6f}" for v in row))
    a = os.path.join(outdir, "slog3_to_dwg_di.cube")
    b = os.path.join(outdir, "dwg_di_to_rec709_g24.cube")
    write_cube(a, size, slog3_to_dwg_di, "S-Log3/S-Gamut3.Cine to DaVinci WG/Intermediate")
    write_cube(b, size, dwg_di_to_rec709_g24, "DaVinci WG/Intermediate to Rec.709 Gamma 2.4")
    for p in (a, b):
        print(f"wrote {p}  ({os.path.getsize(p)/1024:.0f} KB)")
